// Parses the `recommendation` field of a finding. Backend fills SAST/semgrep
// findings with a small, known Markdown shape:
//
//   <principle text>
//
//   **Secure example:**
//
//   ```<lang>
//   <code>
//   ```
//
//   _Example generated by AI — review and adapt to your codebase before applying._
//
// Older / non-SAST findings (gitleaks, osv, DAST) are plain text with no fence.
// This parser is deliberately narrow (no Markdown library needed): it splits off
// the principle, pulls the first fenced code block, and detects the AI
// disclaimer line. Plain text falls through as `principle` only.

export type ParsedRecommendation = {
  principle: string
  codeExample?: { lang: string; code: string }
  aiDisclaimer: boolean
}

// Matches a fenced code block: ```lang\n...code...\n``` (lang optional).
const CODE_FENCE = /```([^\n`]*)\n([\s\S]*?)```/
// The AI disclaimer line, with or without surrounding italic underscores.
const AI_DISCLAIMER = /_?\s*Example generated by AI[^\n]*/i
// The "Secure example:" heading, with or without bold markers / trailing colon.
const SECURE_EXAMPLE_HEADING = /\*{0,2}Secure example:?\*{0,2}/i

export function parseRecommendation(md: string): ParsedRecommendation {
  const text = typeof md === 'string' ? md : ''
  const aiDisclaimer = AI_DISCLAIMER.test(text)

  const fenceMatch = text.match(CODE_FENCE)
  if (!fenceMatch) {
    // Plain text (no code block): the whole string is the principle. Strip any
    // stray disclaimer/heading so plain findings never show literal markdown.
    const principle = text.replace(AI_DISCLAIMER, '').replace(SECURE_EXAMPLE_HEADING, '').trim()
    return { principle, codeExample: undefined, aiDisclaimer: false }
  }

  const lang = fenceMatch[1].trim()
  const code = fenceMatch[2].replace(/\n+$/, '')

  // Everything before the "Secure example:" heading (or the fence itself, if the
  // heading is absent) is the principle.
  const beforeFence = text.slice(0, fenceMatch.index ?? 0)
  const headingMatch = beforeFence.match(SECURE_EXAMPLE_HEADING)
  const principle = (
    headingMatch ? beforeFence.slice(0, headingMatch.index ?? 0) : beforeFence
  ).trim()

  return { principle, codeExample: { lang, code }, aiDisclaimer }
}
