import { describe, it, expect } from 'vitest'
import { parseRecommendation } from './parse-recommendation'

describe('parseRecommendation', () => {
  it('parses a full SAST recommendation with code + AI disclaimer', () => {
    const md =
      'Use parameterized queries or prepared statements. Never build SQL by concatenating or interpolating user input, and apply least-privilege database accounts.\n\n**Secure example:**\n\n```python\ncursor.execute("SELECT * FROM users WHERE id = %s", (user_id,))\n```\n\n_Example generated by AI — review and adapt to your codebase before applying._'
    const result = parseRecommendation(md)
    expect(result.principle).toBe(
      'Use parameterized queries or prepared statements. Never build SQL by concatenating or interpolating user input, and apply least-privilege database accounts.'
    )
    expect(result.codeExample).toEqual({
      lang: 'python',
      code: 'cursor.execute("SELECT * FROM users WHERE id = %s", (user_id,))',
    })
    expect(result.aiDisclaimer).toBe(true)
  })

  it('handles a fence with no language', () => {
    const md = 'Do this.\n\n**Secure example:**\n\n```\nsome code\n```'
    const result = parseRecommendation(md)
    expect(result.codeExample?.lang).toBe('')
    expect(result.codeExample?.code).toBe('some code')
    expect(result.aiDisclaimer).toBe(false)
  })

  it('treats plain text (no fence) as principle only', () => {
    const md = 'Rotate the leaked credential immediately and revoke the old token.'
    const result = parseRecommendation(md)
    expect(result.principle).toBe(md)
    expect(result.codeExample).toBeUndefined()
    expect(result.aiDisclaimer).toBe(false)
  })

  it('does not crash on empty / non-string input', () => {
    expect(parseRecommendation('')).toEqual({
      principle: '',
      codeExample: undefined,
      aiDisclaimer: false,
    })
    // @ts-expect-error exercising the runtime guard for a non-string value
    expect(parseRecommendation(undefined).principle).toBe('')
  })
})
